spring:
  application:
    name: booking-microservice
  profiles:
    active: local #,jsonlog

mongock:
  enabled: true

opentracing:
  jaeger:
    enabled: true

logging:
  level:
    root: info
    org.springframework: warn
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://booking:password@localhost:27017/booking?replicaSet=rs0

server:
  port: 8080

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

web:
  clients:
    car:
      url: http://localhost:8081
    flight:
      url: http://localhost:8082
    hotel:
      url: http://localhost:8083

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://booking:password@mongo:27017/booking?replicaSet=rs0

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent
      port: 6831

web:
  clients:
    car:
      url: http://car-microservice:8080
    flight:
      url: http://flight-microservice:8080
    hotel:
      url: http://hotel-microservice:8080