version: '3.5'
services:

  mongo:
    container_name: mongo
    image: mongo:4.2.8
    restart: always
    hostname: mongo
    environment:
      TZ: UTC # UTC, Europe/Amsterdam, America/Lima
      MONGO_INITDB_DATABASE: booking
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./files/mongo:/docker-entrypoint-initdb.d:ro
    command: mongod --bind_ip_all --replSet rs0
    networks:
      - docker-internal

  mongo-setup:
    container_name: mongo-setup
    image: mongo:4.2.8
    restart: on-failure
    environment:
      #MONGO_REPLICASET_HOST: mongo # [localhost, mongo]
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./files/mongo-setup:/scripts
    entrypoint: [ "/scripts/setup-single.sh" ]
    networks:
      - docker-internal
    depends_on:
      - mongo

  jaeger:
    image: jaegertracing/all-in-one:1.23.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686   #Dashboard port
      - 14268:14268
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - docker-internal

networks:
  docker-internal:
    name: docker-internal
