apiVersion: v1
name: logging
version: 1.0.0
appVersion: 1.0.0
description: Flexible and powerful open source, distributed real-time search and analytics. Kibana is an open source data visualization plugin for Elasticsearch
icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
keywords:
  - elasticsearch
  - kibana
  - fluent-bit
sources:
  - https://github.com/elastic/kibana
  - https://www.elastic.co/products/elasticsearch
  - https://github.com/jetstack/elasticsearch-pet
  - https://github.com/giantswarm/kubernetes-elastic-stack
  - https://github.com/GoogleCloudPlatform/elasticsearch-docker
  - https://github.com/clockworksoul/helm-elasticsearch
  - https://github.com/pires/kubernetes-elasticsearch-cluster
maintainers:
  - name: jsantos
    email: jsantos@email.com
engine: gotpl
home: https://www.elastic.co/products/kibana
