apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  ingress:
    enabled: true
    hosts:
      - jaeger.tracing.com
    annotations:
      kubernetes.io/ingress.class: traefik
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://logging-elasticsearch-client.logging.svc.cluster.local:9200
