apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-cassandra
spec:
  strategy: allInOne
  storage:
    type: cassandra
    options:
      cassandra:
        servers: cassandra
        keyspace: jaeger_datacenter
    cassandraCreateSchema:
      datacenter: "datacenter"
      mode: "test"
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 10
  agent:
    strategy: DaemonSet
