---
apiVersion: v1
kind: Secret
metadata:
  name: logging-fluentd-tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQU5IVlF5TktlTkpOaXhTeDkxVzEzTUF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2MzWmpMV05oZEMxallUQWVGdzB5TVRBMU1Ea3dPREUwTVRCYUZ3MHpNVEExTURjdwpPREUwTVRCYU1CVXhFekFSQmdOVkJBTVRDbk4yWXkxallYUXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURwVnBYZUpzMm8yUE1KdS91blZVSkxKYjczSTNPRU9kZGRxWWRhankzL3luMHcKb2NCa0dSTlpSZ0NEd3NnYmRNcklsWGczcVBVVTIxLytFUWZQelpHR0RwUDRwcVh6blVWZDYxUDVnQ2ZVdlpDTgpyMDFaaitwcFBKTFZsRERGaU1kTnJYeFZFVjJycXd0blk0STgvSnpiZkp2blR2L21HQU5BMCs3U2h6SDNVWFQ5ClBnQWJQK2I0OGtRTW1NRkR3am1yWHNNVzVtbE5vY1VMT09CeEpqdEZ2VTN3dC9Td21CVTl5NUZqemcxTEZSa3oKbmZiNnZySE9TbzJXbmJFS2hGcHVrSzlEYlViNmZkdW51UVZpT1U4ZGFjOW9GS2x3K1dtUVNzRnNNNVVJc011cQphVlpCQXFkUy9lUE1EMHBHNDN6ZUxrRm5pNlF3UTMzRkhKKzJpMHN6QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVEZvU0hDd0pQbVZhai9kOWhLTzlLWVlpU2k1YgpyMmsxQXRHazlFejNjR051UERRQXJXcmJ0TDFvbUlIZTlTTEQwaFgvOUNyMUxJcVltUXI3dnh6YngzeWoxS1NwCmp2YWlDVnl0YW5GM1RxUkN1alhOMXFqSUUzZGpOYThCUnl4SXRqUWR2eHBwUXZKSkFsc3pMaWdVUkdQanM5TU8Ka24rZkY3aHNYRDdjRGRROCtnQU45SGtoUzRyTzJpeXpJQmYwWnl4UnJtM2VLdVlsYlh3aEFMamQ0M2V1SmFzYwp2T090b2pCNXpCa0djNDV6MXpLanphaG9sWGExRk84RHVvSXdVbVpSb0Y4eFBNSkhRaDF2Yjc4bEM3MmRKMU1zCnFxZ2pIc3FmSmF3anZxZWVvc0dKNkI4azhNdHgyTG1ueTZKWmNxNmNNK2d0bWZ5ZzVIa3RTaEcyRFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lRVFBIRWx2RnRITGxndFBhM3lhSUdvREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl4TURVd09UQTRNVFF4TUZvWERUSXlNRFV3T1RBNApNVFF4TUZvd09URTNNRFVHQTFVRUF4TXViRzluWjJsdVp5MWtaVzF2TFdac2RXVnVkR1F1Ykc5bloybHVaeTV6CmRtTXVZMngxYzNSbGNpNXNiMk5oYkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUozc2QwYkYxOXowc1VlKzRaVEs5YUtCMDZudzIrQ0FudkFsWnRqMlpuNGNmam8zbnhkWjFTM1BPc1FZUURCVwpTd25nb2dxMFhraFBYa0RqZjZnOHQyMk83VmJSREFCUzJsVXZNYk5UcVpMMnV0L1pMOXNrVkJmUkxsU3p2SUJNCkpGNGZlWktaTUIycHVVUE10UHhTbVA2Y25Ub0xxbFRGcFMwVnlRd0dtTlcrK1N5czBETXVxd1MxOW9wbnY1ZVEKa2FETTluQndEYTlyMDZSMytQaG4xdXBjbFJQbCtxVGp0aW1RZnBZNlNML3Y3V3NYdlhUVUpMSDlNVmZCdEg2TgpuQStUU1YraWI3N3k1TjVWVWNIRWtnSjVHNDdIUlBHamdPSVZnK1NkQmE5alhiUVU5OCtkT3E1VnM1QnlrcEZ2Cng3eGl5MUtPTXgxdnBZUFU5UDRGNVU4Q0F3RUFBYU0vTUQwd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNYUVN3MkR5c2NEUmxKMnIySVhWUXRWSmZuWFhERTVVeGRYVEdlVHBTWGo2RUx1Wi9ZCnZaRmd4M25hczlFY2FmUW9OZWQ3ZXptQTg4NHJKWC9Oc0gxQTdYT0swcCtDTTJTd240Q3E5TzhVNUVVODI2Y3kKVVFMUk5XVmxtQWszamtzRlNJZHNlK3dOSmtEMGpGSmFXa05QckpGLzlvbTloUHdtcXZ5aTFUWXBaM2lVYXgydAowK3AyeU1lbUl6eXg3clB6T1JqNzBBUzFpSFN3Z01EWnpYYmR5YVlNeVlUUnpvaytwU3lTTENxOEpUZVVRTnIrCjVLSkFUckg0NHY4WmZteStJTVBSMkJVZVlsTnBYSXNmR3dYNWJHS0tKTFBtWm13bkc2OU40NTRGTXZncHROZFMKMytXVHBuVEJVM21DZm9RU0RNa0Fab3B2cjkrK295NjBiczZ5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbmV4M1JzWFgzUFN4Ujc3aGxNcjFvb0hUcWZEYjRJQ2U4Q1ZtMlBabWZoeCtPamVmCkYxblZMYzg2eEJoQU1GWkxDZUNpQ3JSZVNFOWVRT04vcUR5M2JZN3RWdEVNQUZMYVZTOHhzMU9wa3ZhNjM5a3YKMnlSVUY5RXVWTE84Z0V3a1hoOTVrcGt3SGFtNVE4eTAvRktZL3B5ZE9ndXFWTVdsTFJYSkRBYVkxYjc1TEt6UQpNeTZyQkxYMmltZS9sNUNSb016MmNIQU5yMnZUcEhmNCtHZlc2bHlWRStYNnBPTzJLWkIrbGpwSXYrL3RheGU5CmROUWtzZjB4VjhHMGZvMmNENU5KWDZKdnZ2TGszbFZSd2NTU0Fua2Jqc2RFOGFPQTRoV0Q1SjBGcjJOZHRCVDMKejUwNnJsV3prSEtTa1cvSHZHTExVbzR6SFcrbGc5VDAvZ1hsVHdJREFRQUJBb0lCQUdHVWpuTUZwb2RhRHZ6RQovb0JCRkp4UVdpaGtzb2c3RVhwVHNnUVg1R2JDVm1ERW82SDdHUlZRT2dDVzkzcW1wNEUzOHdob1FPV3ZYUTc5ClE1RUJ5MWwvK2prdHZKdXFsa3dTZUVSVlNxK0xreGJrRFlUOElwWUE0LzdrZkhKT0doNnFsaVUyVUp2VGxxMUYKSFFQWVNiN3hxTmtJQWp5VlQ2WFhFejVDQ1VmdzJ6R0l1a0NKRDdSQTJyeWVMODVXVjdrN2FPWUZvenZueVVmbApmSk1CdkZ5K2RGOWJoSXFreFhiUEtTMjgyWDhqTjNxR2NVM0MxU2I1YTlPYWRYUzU4K1poZS9uMFdINjdLNFNaClE5UnlzN2VvQnFCcTdXWGJmVFpFbmgrTDkxTmh3UUlTT0cxVUY4WFRkVlV1c05PM0NPcXU3QUpSWFZTTWRuWGYKV0tsYkZra0NnWUVBMGZTK093eXJmQktKb01FWHJaK01TbHFINXZ5YUIxRVBQY0o4dzh5SWVBS3pQa0U1V0xpZApIRmlwYnFsMnM5bS82aEhwWms5YzVMbGJJQ1NTRkRBUW9ETnBnL2ZmVnovNGRFalQwcVRtOTNTT2ZjWENPRjZMCjlkcGNnaUREZ0xFMVRtb3Vmb09tZ0RjeXVFaXhJSW0vZGxYQXUvaGJRNWRNNjd0YW45U0pydXNDZ1lFQXdJNk0KQ0s5M0dka25oOWJTcUFHZjl0YkkxOVpRS29neFV3NnRlb1NmTTlOTFBTaGl0Tll2Z0J1bzdQVzFpSDcyRWZkRwp1eHJZS2NPYU9yMTVFTmgxVGlSY2xVNTVGWHJqNVJCbFpNQzNWK1UzSTdwaG5yUWZ1UmVVS1VHT3R2N3h3UUJCCnJsN3VuNHc4dkVZRVd0N3U1S1k1aUE4RXBNQXFHbWpDM1lGbzhpMENnWUVBd002WXczRm5LWkY4Z2Z2UTJzamgKOUlZZXQ2alJhbGF1UUhFU1VsektGaXVrbjA4V2NydFd6R2svYnppQW9ia2QzTDZHTUVaQmNHb25uT1Q0b1VGaQpnenV6Y2xWMjdKRDZnUTlBTnZqb2dlYXYxQ0IvczNSZjQyNmI5WVJSQlNXM1prTnNYeEpYSFBlVHhGZzlFVHh1CmJ5VmcwVDNKMGRCbit6TWFqaHlJTS9FQ2dZQVhucVN3d0ExRS8yMG83WUlEbDhkdWVPUkVEWWJoNExqa0xrMjcKVko5T3RTRnFqQlNuaUFwbGxYOEFLaGV0ZVoxbmtNUjlXUXFnL054alRqQ1dqMmE4UWh1Vk9QNERVNEsyNjI3MApqK3N0ZmZGb2tZazk5V3hhd1Bpc290MEZ0M29pS1l6ay9jSVpraE0xS1FXSnZBVGp5VHdQWTRBM1VWY1l6RGJ6CkF0ZkR0UUtCZ0dHWDV3RTZvVDRxWXM3WVZXZjFGODZHQW02aHNqZFdyWm1OY0Y0Ym9Oc2ZsSFljaVBwR0RXYm0KbDkyQmpBOUpZYkJwRlF1Q1N0SGRoNkhsUEhXcW55aEp1WlUwUXFlRDBFYmR4QnVCWmZsMllMaFFLN0NuRUlKdQp5TjVzTlZVcTlpSmZBRXRuRkNKN25adlhoUzhHbW9IU1MrZ0pzY0NPaVpnbk14ekJ5MGwwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: logging-fluentbit-tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQU5IVlF5TktlTkpOaXhTeDkxVzEzTUF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2MzWmpMV05oZEMxallUQWVGdzB5TVRBMU1Ea3dPREUwTVRCYUZ3MHpNVEExTURjdwpPREUwTVRCYU1CVXhFekFSQmdOVkJBTVRDbk4yWXkxallYUXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURwVnBYZUpzMm8yUE1KdS91blZVSkxKYjczSTNPRU9kZGRxWWRhankzL3luMHcKb2NCa0dSTlpSZ0NEd3NnYmRNcklsWGczcVBVVTIxLytFUWZQelpHR0RwUDRwcVh6blVWZDYxUDVnQ2ZVdlpDTgpyMDFaaitwcFBKTFZsRERGaU1kTnJYeFZFVjJycXd0blk0STgvSnpiZkp2blR2L21HQU5BMCs3U2h6SDNVWFQ5ClBnQWJQK2I0OGtRTW1NRkR3am1yWHNNVzVtbE5vY1VMT09CeEpqdEZ2VTN3dC9Td21CVTl5NUZqemcxTEZSa3oKbmZiNnZySE9TbzJXbmJFS2hGcHVrSzlEYlViNmZkdW51UVZpT1U4ZGFjOW9GS2x3K1dtUVNzRnNNNVVJc011cQphVlpCQXFkUy9lUE1EMHBHNDN6ZUxrRm5pNlF3UTMzRkhKKzJpMHN6QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBVEZvU0hDd0pQbVZhai9kOWhLTzlLWVlpU2k1YgpyMmsxQXRHazlFejNjR051UERRQXJXcmJ0TDFvbUlIZTlTTEQwaFgvOUNyMUxJcVltUXI3dnh6YngzeWoxS1NwCmp2YWlDVnl0YW5GM1RxUkN1alhOMXFqSUUzZGpOYThCUnl4SXRqUWR2eHBwUXZKSkFsc3pMaWdVUkdQanM5TU8Ka24rZkY3aHNYRDdjRGRROCtnQU45SGtoUzRyTzJpeXpJQmYwWnl4UnJtM2VLdVlsYlh3aEFMamQ0M2V1SmFzYwp2T090b2pCNXpCa0djNDV6MXpLanphaG9sWGExRk84RHVvSXdVbVpSb0Y4eFBNSkhRaDF2Yjc4bEM3MmRKMU1zCnFxZ2pIc3FmSmF3anZxZWVvc0dKNkI4azhNdHgyTG1ueTZKWmNxNmNNK2d0bWZ5ZzVIa3RTaEcyRFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzekNDQWNlZ0F3SUJBZ0lSQUpUNkRpa1IxYkFDV0FvYURPeFhsd1l3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2MzWmpMV05oZEMxallUQWVGdzB5TVRBMU1Ea3dPREUwTVRCYUZ3MHlNakExTURrdwpPREUwTVRCYU1BQXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdTJXenpPQ05uCjZaVGtFNk82a0V1TXVPcXVQYjA2c014SXNsTFptSzZtNTI0VHNRSTc3RmdneGZCVEE1OUU5ckg0WWJXalB4V3UKendocHpLSGJzcGN2NkdFQ0g1RjM5dzVtYjFvL2d0YTdjYXdVejJpTDN4MUduYWk1M0F4U1RYeXlhS29obHptLwo1MnArdVI1L0ZDeXhmWFFkOFNuL3hYQmx1TGo2NXNDMHdQS0dhanZNbnd0eHN6NHkyU25sd3dhRlBKRWQrVFVHCjZsMlNOcVloUnl2MzByU1lMQzUrN3dFUzV5d3U4bjloVmlJU2ZURHk5UnJnbHdtblZTeW5Gckl3TzUzbHJEcGcKdDgxTGJzbmRaV2VvS0d2M2RraDBkUzc5cGF5VDlSN0g1S0FkV1V2K0hObGtvTENxc2t1VDRyREQ3eEtGQm5RQwpTNGJSKzZYYjIwWDdBZ01CQUFHalB6QTlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyCkJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFOQmdrcWhraUc5dzBCQVFzRkFBT0MKQVFFQUQ3VUV5N2NqLzJBamgvZEx4eHdzVlQzdGpHc0FUemhrY0k4R29pcTJ5OHh2aEdQem9neTlBaDNjd2V1RQpOeUNWMzQvb3R2aW5OZ1lmYnQySEsyajVBTk5jUDBTMC9HelJ0ZXZHMEpQbEtwMzk0YXNDZmt1bVZ0UUVsQkhVClpDQkIvYmFFcnNWQVRWdkdyUk0rMnlGVzRJcDR1aFZpc0JHa0UzTG5IWVRVWmdWcVQ0YTNUdVZ5N29HaWJkNysKait3R2V2S1pTNVJBc2Y4MjI4b0F2Z0xwRlVJR3liUDg2R1poZWhDRWlTYjB0VlpQN1JkckRvTVp5ejNwREx5cApCall5dFUwTUVhZXZEYUZndHI5NmFWdmo0amxyK1VhcjU3d3VLN1hWY0hDVGsxTWxQNjVLaU9sM3FINEluUFRpCkxjb1F6a3dBZ1FDVmpjeWZFY2xRVU42SmpBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcnRsczh6Z2paK21VNUJPanVwQkxqTGpxcmoyOU9yRE1TTEpTMlppdXB1ZHVFN0VDCk8reFlJTVh3VXdPZlJQYXgrR0cxb3o4VnJzOElhY3loMjdLWEwraGhBaCtSZC9jT1ptOWFQNExXdTNHc0ZNOW8KaTk4ZFJwMm91ZHdNVWsxOHNtaXFJWmM1ditkcWZya2VmeFFzc1gxMEhmRXAvOFZ3WmJpNCt1YkF0TUR5aG1vNwp6SjhMY2JNK010a3A1Y01HaFR5UkhmazFCdXBka2phbUlVY3I5OUswbUN3dWZ1OEJFdWNzTHZKL1lWWWlFbjB3Cjh2VWE0SmNKcDFVc3B4YXlNRHVkNWF3NllMZk5TMjdKM1dWbnFDaHI5M1pJZEhVdS9hV3NrL1VleCtTZ0hWbEwKL2h6WlpLQ3dxckpMaytLd3crOFNoUVowQWt1RzBmdWwyOXRGK3dJREFRQUJBb0lCQUJ4MDBtQjdJSGdHOGU1MApxODd2TVB5RUU5MnJ1cUpVcDhxbEN3clM2SW5OWElMajZnTXFvZVVqa2N0UTZaamx0VzFCS2JpWnljT2JlamtOCnpzSGN2UEpWRllTczhwWGRwWUJTV3hPL0RZZVFKbnQwamdWRm1KUW5rSkEvR2RwRE5pb3JFcFZJOFdNa0hKYm4KTmVsa3RTbGx5NEliLzhQYXRFSTU0QkVsZ1BOcHRva3NhN1J0bG4wSHhjR0h2NzBuRkU3SjdFL1FPd29SZDlMUQo2YzJCS2I5bUUvWEJ4WEpJcStrcnE4Uy8xR0wxSE9Ud0dtR1YrZUtQdldJaitkd3NjVVR3RVRtaFgzQlo2c2dTCkhVMXgwdUlzV2pucC9HbzZPMllUNllWdFlLK1FwRGpOWTdPeWRwbWNGUXN3YURENFc5UHg4SC9xY055N01yNHAKTGF3Q1VzRUNnWUVBNGxGeDY3ZVJFa0UrNVZEM2o2Y25pSktzUjZjL0pjUnFwNXlTNVRvbDhFdVJKUmJNb0FIUwp0VlJuWGNTR2pqTGUyMmFLS0c4UFhsOGd0UjJqQ0c0V2s1QmVJQ1pjZ252VzlUbHhWd3V0eTcrTUk3WnQzd3ZQCjZiVzk5ZitwUGtCcU4wNDM4cnFOSlRWOFVuNEZ5OHNiZmZ0ZFJmOFVBNjJYSTdWQUdZZytOZXNDZ1lFQXhjZnUKcEtTbUJtQVJNNzZvc0VHY3FERjljWUV0cmFtWTNmQndDaGp2Q2pkZmUxa2E3bklFM2FFSkVvV1oybzJlc0trOAp1L1U1VW9DUEppdDdPZDVReHkySnVOaWtnNVBSRW1UcTd6U2YxdlBRUW9rSVFvVnVqbUhMbDlOQk43cGdvd3pTCnpiMjVtblBwK3dTT2R0S2JCRGFaRmE3clJJWWxjbVIvdll5WDNERUNnWUVBMCsya21qRUpubWlPdHpwOHVINjAKM0lWTTRzUlFzOU1jZE55QUNqdkxieHUwVFdEdU9SKzc2cVdoTGdOc1pSaHA3RlkzSmVucUlGdEFTNW4zSTF2RAp0R2RLWFJ6UElEbExiOU5jdVVCc2ZSRmY3OGxUVmJ5Lzg0Q0c1Q2VHbW83RGFBck5CWFYvMnNvZEl6cHp2d1R4Ck42WDlFQ0R1NHdyWkwwejVPMitEb2dVQ2dZQklQMVNKaUN1dHdJSUlLT2x1R1Vta2x3OS8ydlJZcjg5TG8zMEoKOHptK3ZhTi9aM2xUQ1F1RitrRmFKcnVnL29LdGZlVFZ0Q3FRWEszdC80d3dBMm4ybUVmcTRoaVdoL1NqaDRIYQpoNXFyNXJ4NDBaM1d6dThueThtWFdIQkdieXJGNVBWTWVyWEdHZm1xM0dzK05JaXo3VTNXZ2VNblVPbDA5QWxGCnNJbjR3UUtCZ0FaNGxiZFQzcVdFVlFmejV2TFU1Zm8wNFo5NmVBZVpFUmlVSUtwTmZPdGhRQ0E5YWFMeTIzZkoKVUlHUkVGak9ZT0RVQWMwVU1mMEN6SDJDZUtxRS9XL0haUmVzdm5lU3lqb2hyci9KeGRMQ3FUN1FHTzJkbjhoOAo4UXNLeWVCdXRvL3VIZStWVlpGbkgwekZlbGRDQ2x4VzZwTEp0cEJ1MVFmUk02aVJDb2llCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: logging.banzaicloud.io/v1beta1
## The flows can be either Flow or ClusterFlow
kind: ClusterFlow
metadata:
  name: logging-flow
  namespace: logging
spec:
  filters:
    - tag_normaliser: {}
      # format: cluster1.${namespace_name}.${pod_name}.${labels.app}
    #- record_transformer:
    #    remove_keys: $.kubernetes.annotations
    #- parser:
    #    remove_key_name_field: true
    #    reserve_data: true
    #    parse:
    #      type: multi_format
    #      patterns:
    #      - format: json
    #      - format: none
    #      #- format: nginx
    #      #- format: regexp
    #      #  expression: '/^(?<time>[^\]]*) \[(?<level>[^ ]*)\] (?<source>[^\":]*): (?<message>.*)$/'
    #      # time_key: logtime
    #      #  time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
  match:
    - select: {}
  #     labels:
  #       app.kubernetes.io/name: log-generator
  #       app.kubernetes.io/instance: log-generator
  #      namespaces:
  #      - kube-system
  #      - logging
  globalOutputRefs:
    - logging-output-elasticsearch
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  fluentd:
    tls:
      enabled: true
      secretName: logging-fluentd-tls
      sharedKey: ""
    #metrics:
    #  serviceMonitor: true

  fluentbit:
    tls:
      enabled: true
      secretName: logging-fluentbit-tls
      sharedKey: ""
    #metrics:
    #  serviceMonitor: true
    inputTail:
      Refresh_Interval: "60"
      Rotate_Wait: "5"
    bufferStorage:
      storage.backlog.mem_limit: 256KB

  ## The operator evaluates clusteroutputs in the controlNamespace only unless allowClusterResourcesFromAllNamespaces is set to true.
  allowClusterResourcesFromAllNamespaces: true
  controlNamespace: logging
  # It is possible to monitor only the desired namespaces
  #watchNamespaces: ["kube-system", "logging"]
---
apiVersion: logging.banzaicloud.io/v1beta1
## The outputs can be either Output (localOutputRefs) or ClusterOutput (globalOutputRefs)
kind: ClusterOutput
metadata:
  name: logging-output-elasticsearch
  namespace: logging
spec:
  elasticsearch:
    host: elastic-cluster-es-http.logging
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    # Included logstash format
    #logstash_format: true
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: elastic-cluster-es-elastic-user
          key: elastic
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
