apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  #namespace: tools
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
spec:
  type: ClusterIP
  ports:
  - name: traefik
    port: 9000
    targetPort: traefik
    protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  traefik
  #namespace: tools
  labels:
    app: traefik
    release: prometheus
spec:
  jobLabel: traefik-metrics
  endpoints:
  - port: traefik
    path: /metrics
  namespaceSelector:
    matchNames:
    - tools
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-dashboard
 
