apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  traefik
  namespace: tools
  labels:
    app: traefik
    release: prometheus-stack
spec:
  jobLabel: traefik-metrics
  endpoints:
  - port: traefik
    path: /metrics
  namespaceSelector:
    matchNames:
    - tools
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik-dashboard
 
