apiVersion: v1
description: Template to deply microservice build on Spring Boot.
name: microservice
version: 0.1.0
appVersion: 0.0.1-SNAPSHOT
home: https://spring.io/
sources:
- https://github.com/spring-projects/spring-boot
icon: https://spring.io/img/spring-by-pivotal-9066b55828deb3c10e27e609af322c40.png
maintainers:
- name: jsantosa
  email: jsantosa@email.com
