spring:
  application:
    name: order-service
  profiles:
    active: local
  liquibase:
    change-log: classpath:liquibase/master.xml
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure.include: health,info,prometheus
      path-mapping:
        prometheus: /metrics

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.group.ecommerce: DEBUG

---
spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://dockerhost:5432/ordering
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

services:
  catalog:
    endpoint: http://localhost:8081/api/v1
---
spring:
  profiles: docker
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgres:5432/ordering
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

services:
  catalog:
    endpoint: http://catalog-service:8080/api/v1