dependencies:
  - name: prometheus
    version: 8.11.4
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: grafana
    version: 3.3.10
    repository: https://kubernetes-charts.storage.googleapis.com/