openapi: 3.0.3
info:
  title: Booking API
  description: Microservice API to manage bookings
  version: 1.0.0
tags:
  - name: booking
    description: Booking
servers:
  - url: /api/v1
paths:
  /bookings:
    get:
      tags:
        - booking
      summary: findAllBookings
      operationId: findAllBookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - booking
      summary: save
      operationId: saveBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bookings/{id}:
    get:
      tags:
        - booking
      summary: findBookingById
      operationId: findBookingById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - booking
      summary: deleteBooking
      operationId: deleteBooking
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Booking:
      title: Booking
      type: object
      properties:
        active:
          type: boolean
        clientId:
          type: string
        createdAt:
          type: string
          format: date-time
        fromDate:
          type: string
          format: date-time
        id:
          type: string
        vehicleId:
          type: string
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
