openapi: 3.0.3
info:
  title: Booking API
  description: Microservice API to manage bookings
  version: 1.0.0
tags:
  - name: booking-controller
    description: Booking Controller
servers:
  - url: /api/v1
paths:
  /bookings:
    get:
      tags:
        - booking-controller
      summary: findAllBookings
      operationId: findAllBookings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - booking-controller
      summary: save
      operationId: saveBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Booking'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bookings/{id}:
    get:
      tags:
        - booking-controller
      summary: findBookingById
      operationId: findBookingById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - booking-controller
      summary: deleteBooking
      operationId: deleteBooking
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Booking:
      title: Booking
      type: object
      required:
        - id
        - clientId
        - fromDate
        - toDate
      properties:
        id:
          type: string
          maxLength: 64
          example: b9460d0a-248e-11e9-ab14-d663bd873d93
        active:
          type: boolean
        clientId:
          type: string
          maxLength: 64
          example: 8fb3c723-7851-486e-a369-ba0f9b908198
        fromDate:
          type: string
          format: date-time
        toDate:
          type: string
          format: date-time
        vehicleId:
          type: string
          maxLength: 64
          example: 4cc0fa38-533e-46b7-bdf6-0e59b20b0d84
        flightId:
          type: string
          maxLength: 64
          example: e8a58cfc-71bb-4ea3-aebe-147590a5fc15
        hotelId:
          type: string
          maxLength: 64
          example: 72ac9ab5-685a-437c-8204-361399f2f65c
        createdAt:
          type: string
          format: date-time
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
