openapi: 3.0.3
info:
  title: Car Rental API
  description: Microservice API to manage Car Booking
  version: 1.0.0
tags:
  - name: vehicle-controller
    description: Vehicle Controller
servers:
  - url: /api/v1
paths:
  /vehicles:
    get:
      tags:
        - vehicle-controller
      summary: findAllVehicles
      operationId: findAllVehicles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - vehicle-controller
      summary: save
      operationId: saveVehicle
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /vehicles/{id}:
    get:
      tags:
        - vehicle-controller
      summary: findVehicleById
      operationId: findVehicleById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - vehicle-controller
      summary: deleteVehicle
      operationId: deleteVehicle
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Vehicle:
      title: Vehicle
      type: object
      properties:
        brand:
          type: string
        color:
          type: string
        engineCapacity:
          type: number
          format: double
        fuel:
          type: string
        id:
          type: string
        kms:
          type: integer
          format: int32
        model:
          type: string
        seats:
          type: integer
          format: int32
        year:
          type: string
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
