openapi: 3.0.3
info:
  title: Flight API
  description: Microservice API to manage Flight
  version: 1.0.0
tags:
  - name: flight-controller
    description: Flight Controller
servers:
  - url: /api/v1
paths:
  /flights:
    get:
      tags:
        - flight-controller
      summary: findAllFlights
      operationId: findAllFlights
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - flight-controller
      summary: save
      operationId: saveFlight
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Flight'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /flights/{id}:
    get:
      tags:
        - flight-controller
      summary: findFlightById
      operationId: findFlightById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flight'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - flight-controller
      summary: deleteFlight
      operationId: deleteFlight
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Flight:
      title: flight
      type: object
      required:
        - id
        - number
        - source
        - destination
        - departure
        - arrival
      properties:
        id:
          type: string
          maxLength: 64
          example: b9460d0a-248e-11e9-ab14-d663bd873d93
        number:
          type: integer
          format: int32
          maximum: 2147483647
          minimum: 0
          example: 1234
        source:
          type: string
          maxLength: 256
          example: Amsterdam, Netherlands (AMS)
        destination:
          type: string
          maxLength: 256
          example: Terminal 4 - T4 Madrid Airport (MAD)
        departure:
          type: string
          format: date-time
        arrival:
          type: string
          format: date-time
        seats:
          type: integer
          maximum: 9999
          minimum: 0
          example: 853
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
