openapi: 3.0.3
info:
  title: Hotel Boking API
  description: Microservice API to manage Hotel Booking
  version: 1.0.0
tags:
  - name: hotel-controller
    description: Hotel Controller
servers:
  - url: /api/v1
paths:
  /hotels:
    get:
      tags:
        - hotel-controller
      summary: findAllHotels
      operationId: findAllHotels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - hotel-controller
      summary: save
      operationId: saveHotel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hotel'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /hotels/{id}:
    get:
      tags:
        - hotel-controller
      summary: findHotelById
      operationId: findHotelById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - hotel-controller
      summary: deleteHotel
      operationId: deleteHotel
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Hotel:
      title: hotel
      type: object
      required:
        - id
        - name
        - address
        - city
        - country
        - rooms
      properties:
        id:
          type: string
          maxLength: 64
          example: b9460d0a-248e-11e9-ab14-d663bd873d93
        name:
          type: string
          maxLength: 256
          example: Address Dubai Marina
        address:
          type: string
          maxLength: 256
          example: Al Marsa Street, 66 Dubai Marina, Dubai United Arab Emirates
        postalCode:
          type: string
          maxLength: 32
          example: 32923
        city:
          type: string
          maxLength: 256
          example: Dubai
        country:
          type: string
          maxLength: 128
          example: United Arab Emirates
        rooms:
          type: integer
          format: int32
          maximum: 99999
          minimum: 0
          example: 3
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
