openapi: 3.0.3
info:
  title: Hotel Boking API
  description: Microservice API to manage Hotel Booking
  version: 1.0.0
tags:
  - name: hotel-controller
    description: Hotel Controller
servers:
  - url: /api/v1
paths:
  /hotels:
    get:
      tags:
        - hotel-controller
      summary: findAllHotels
      operationId: findAllHotels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Hotel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - hotel-controller
      summary: save
      operationId: saveHotel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hotel'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /hotels/{id}:
    get:
      tags:
        - hotel-controller
      summary: findHotelById
      operationId: findHotelById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - hotel-controller
      summary: deleteHotel
      operationId: deleteHotel
      parameters:
        - name: id
          in: path
          description: id
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    Hotel:
      title: hotel
      type: object
      properties:
        brand:
          type: string
        color:
          type: string
        engineCapacity:
          type: number
          format: double
        fuel:
          type: string
        id:
          type: string
        kms:
          type: integer
          format: int32
        model:
          type: string
        seats:
          type: integer
          format: int32
        year:
          type: string
  securitySchemes:
    jwt:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
security:
  - jwt: []
