apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "micro.fullname" . }}
  labels:
    app: {{ template "micro.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
