kind: Service
apiVersion: v1
metadata:
  name: {{ template "micro.fullname" . }}
  labels:
    app: {{ template "micro.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  # If you are running k8s on a local dev box, you can use type NodePort instead
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
{{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
{{- else }}
      targetPort: 8080
{{- end}}
      name: service
  selector:
    app: {{ template "micro.name" . }}
    component: server
    release: {{ .Release.Name }}
