architecture: standalone
useStatefulSet: false

auth:
  enabled: true
  rootPassword: password

disableJavascript: false
enableJournal: true

initdbScripts:
  init_monitor_script.js: |
    use admin
    db.createUser({
      user: 'monitor',
      pwd: 'password',
      roles: [
          {
              role: 'clusterMonitor',
              db: 'admin',
          },
          {
              role: 'read',
              db: 'local',
          }
      ],
    });
  init_databases_script.js: |
    use db_1
    db.createUser({
      user: 'user',
      pwd: 'password',
      roles: [
          {
              role: 'readWrite',
              db: 'db_1',
          },
      ],
    });

    db = db.getSiblingDB('db_1')

    db.createCollection('test', { capped: false });

    db.test.insert([
        { "item": 1 },
        { "item": 2 },
        { "item": 3 },  
        { "item": 4 },
        { "item": 5 }
    ]);

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

