spring:
  application:
    name: spring-boot-tracing
  profiles:
    active: local

server:
  port: 8080
  shutdown: graceful

opentracing:
  jaeger:
    enabled: true
    service-name: ${SPRING_APPLICATION_NAME:spring-boot-tracing}

# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
#  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
#  spring.boot.version: @spring-boot.version@

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health:
      show-components: always
      probes.enabled: true
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
      base-path: /management
      path-mapping:
        prometheus: /metrics

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.tracing: DEBUG

---
spring:
  profiles: local

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

---
spring:
  profiles: docker

opentracing:
  jaeger:
    udp-sender:
      host: jaeger-agent
      port: 6831
