spring:
  application:
    name: car-microservice
  profiles:
    active: local

mongock:
  enabled: true
  change-logs-scan-package:
    - com.example

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health

logging:
  level:
    root: info
    org.springframework: warn

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://booking:password@localhost:27017/booking?replicaSet=rs0

server:
  port: 8083
---
spring:
  profiles: docker
  data:
    mongodb:
      uri: mongodb://booking:password@mongo:27017/booking?replicaSet=rs0
