spring:
  application:
    name: car-microservice
  profiles:
    active: local #,jsonlog

server:
  port: 8080
  shutdown: graceful

mongock:
  enabled: true

logging:
  level:
    root: info
    org.springframework: warn
    com.example: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://booking:password@localhost:27017/booking?replicaSet=rs0

server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://booking:password@mongo:27017/booking?replicaSet=rs0
